### ISSUE TITLE
Make all the pages responsive

### ISSUE THREAD

**Issue by r-kohale9** [beingtmk/nodejs-starter-kit#15]
- [x] SignIn page
- [x] Signup page
- [x] Profile page

**Comment by beingtmk** [comment]
- [x] User - admin panel

**Comment by r-kohale9** [comment]
- [x] reset password
- [x] useradd
- [x] useredit
- [x] uploads
- [x] reports
- [x] posts
- [x] post/:id
- [x] post/new
