### ISSUE TITLE
Quiz Module

### ISSUE THREAD

**Issue by lokeshrana9999** [beingtmk/nodejs-starter-kit#43]
Implement a quiz module that has the functionality of creating custom quizzes (question and associated answers). Also users should be able to answer each question and report card be made available to admin.

**Comment by beingtmk** [comment]
4 tables
1. question: tag, description, is_active, quiz_id
2. choice: description, question_id
3. answer: user_id, question_id, answer_id
4. quiz: title, description

**Comment by beingtmk** [comment]
/quiz:
* Stepped form for all active questions

**Comment by beingtmk** [comment]
a table of results for all members needs to be added. @lokeshrana9999.
