### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by louisdauvois** [beingtmk/nodejs-starter-kit#69]
In the documentation you ask to : 

`git clone -b stable https://github.com/beingtmk/nodejs-starter-kit.git`

but there is no stable branch, maybe change it to **master branch**

`git clone -b master https://github.com/beingtmk/nodejs-starter-kit.git`

**Comment by r-kohale9** [comment]
Yes, that is correct, a proper update for Readme is needed #17 (an issue is already opened to address all these issues).

**Comment by lokeshrana9999** [comment]
Closing this wrt https://github.com/beingtmk/nodejs-starter-kit/pull/67
